export { useStore } from './store';

export const SAVE_PROPOSAL_HEADER_FIELD = 'SAVE_PROPOSAL_HEADER_FIELD';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const RETRIEVE_PRICES = 'RETRIEVE_PRICES';
export const CHECKED_PRODUCTS = 'CHECKED_PRODUCTS';
export const EDIT_PRODUCTS = 'EDIT_PRODUCTS';
export const SAVE_PROPOSAL = 'SAVE_PROPOSAL';
export const CANCEL_PROPOSAL = 'CANCEL_PROPOSAL';
export const LOADING_BAR = 'LOADING_BAR';
export const SAVE_PROPOSAL_ID_TYPE = 'SAVE_PROPOSAL_ID_TYPE';
